<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MeshRegistration.Algorithms.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MeshRegistration.Core\MeshRegistration.Core.csproj" />
    <ProjectReference Include="..\..\src\MeshRegistration.IO\MeshRegistration.IO.csproj" />
    <ProjectReference Include="..\..\src\MeshRegistration.Algorithms\MeshRegistration.Algorithms.csproj" />
  </ItemGroup>

</Project>
